### PR TITLE
docs(widgets_with_holes): add missing quote in tpl example in 02_widgets _with_holes README

### PR DESCRIPTION
**Pull request by hsablonniere**

### CODE REVIEW

**Comment by stefanhoth** [comment]
+1 fixed this in my repo, too.

**Comment by pkozlowski-opensource** [comment]
Awesome, thnx for taking time to open a PR @hsablonniere ! 
Landed as 4e3c0cbcd91ec174a609b96fff26ca69c6ba4e29.

**Comment by hsablonniere** [comment]
No worries. I'm actually @ Devoxx doing the workshop :p

**Comment by pkozlowski-opensource** [comment]
Cool, have fun @hsablonniere !

**Pull request closed without merging**
